# Generated by Django 4.0.4 on 2022-04-29 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'verbose_name': 'snippet', 'verbose_name_plural': 'snippets'},
        ),
        migrations.AlterModelTable(
            name='snippet',
            table='snippets',
        ),
    ]
