services:
  db:
    build: .
    container_name: test-db

    ports:
      - published: 5432 # container port
        target: 5432 # published port via access from outer docker engine

    volumes:
      - type: volume
        source: sql-test
        target: /var/lib/postgresql/data

      - type: bind
        source: ./init/1.sql
        target: /docker-entrypoint-initdb.d/init.sql

    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  sql-test:
