sqlmigrate:
	python3 manage.py sqlmigrate snippets 0001_initial

sqlmigrate2:
	python3 manage.py sqlmigrate snippets 0002_alter_snippet_options_alter_snippet_table

sqlmigrate3:
	python3 manage.py sqlmigrate snippets 0003_tag_comment
