# Generated by Django 4.0.4 on 2022-04-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0002_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="created_at",
            new_name="commented_at",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="created_by",
            new_name="commented_by",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="snippet",
            new_name="commented_to",
        ),
    ]
