--------------------
--- films
--------------------
CREATE TABLE films (
    code        char(5) CONSTRAINT firstkey PRIMARY KEY,
    title       varchar(40) NOT NULL,
    did         integer NOT NULL,
    date_prod   date,
    kind        varchar(10),
    len         interval hour to minute
);

-- insert a row without 'VALUE[S]' syntax
INSERT INTO films (code, title, did, date_prod, kind)

VALUES
  ('T_601', 'Yojimbo', 106, '1961-06-16', 'Drama')
;


-- insert a row using VALUES
INSERT INTO films
  VALUES ('UA502', 'Bananas', 105, '1971-07-13', 'Comedy', '82 minutes')
;

-- insert multiple row 
INSERT INTO films (code, title, did, date_prod, kind)
VALUES
  ('B6717', 'Tampopo', 110, '1985-02-10', 'Comedy'),
  ('HG120', 'The Dinner Game', 140, DEFAULT, 'Comedy')
;


--------------------
--- distributors
--------------------
CREATE TABLE distributors (
     did    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     name   varchar(40) NOT NULL CHECK (name <> '')
);

INSERT INTO distributors (did, name)
VALUES (5, 'Gizmo Transglobal'),
       (6, 'Associated Computing, Inc')
;
