services:
  web:
    build:
      context: .
      dockerfile: DockerFile

    command: python /code/manage.py runserver 0.0.0.0:8000

    volumes:
      - type: bind
        source: .
        target: /code

    ports:
      - published: 8000
        target: 8000

  db:
    image: postgres:14
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
